# Generated by Django 2.2.5 on 2019-12-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_train_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='day',
            field=models.ManyToManyField(to='home.Day'),
        ),
    ]
